In [48]:
import numpy as np
import xarray as xr

from metrics import WeightedRMSE

In [49]:
rmse = WeightedRMSE(num_latitudes=121)

In [50]:
x = np.random.rand(1, 3, 20, 10)
rmse(x, x)


ValueError: Number of latitudes (10) must match the number of latitudes used to calculate the weights (121).

In [51]:
ds = xr.open_zarr(
    "gs://gcp-public-data-arco-era5/ar/1959-2022-6h-240x121_equiangular_with_poles_conservative.zarr/",
    chunks=None,
    storage_options=dict(token="anon"),
)

ds = ds.sel(time=slice("2010-01-01", "2010-01-10"))
ds

<xarray.Dataset> Size: 503MB
Dimensions:                                           (time: 40,
                                                       longitude: 240,
                                                       latitude: 121, level: 13)
Coordinates:
  * latitude                                          (latitude) float64 968B ...
  * level                                             (level) int64 104B 50 ....
  * longitude                                         (longitude) float64 2kB ...
  * time                                              (time) datetime64[ns] 320B ...
Data variables: (12/38)
    10m_u_component_of_wind                           (time, longitude, latitude) float32 5MB ...
    10m_v_component_of_wind                           (time, longitude, latitude) float32 5MB ...
    10m_wind_speed                                    (time, longitude, latitude) float32 5MB ...
    2m_temperature                                    (time, longitude, latitude) float32 5MB ...
    angle_of_sub_gridscale_orography                  (longitude, latitude) float32 116kB ...
    anisotropy_of_sub_gridscale_orography             (longitude, latitude) float32 116kB ...
    ...                                                ...
    type_of_high_vegetation                           (longitude, latitude) float32 116kB ...
    type_of_low_vegetation                            (longitude, latitude) float32 116kB ...
    u_component_of_wind                               (time, level, longitude, latitude) float32 60MB ...
    v_component_of_wind                               (time, level, longitude, latitude) float32 60MB ...
    vertical_velocity                                 (time, level, longitude, latitude) float32 60MB ...
    wind_speed                                        (time, level, longitude, latitude) float32 60MB ...

In [ ]:
da = ds["geopotential"].sel(level=500)
da

x, y = da[0].data, da[22].data
x, y = np.expand_dims(x, 0), np.expand_dims(y, 0)


array([970.1321554])

In [54]:
%timeit rmse(x, y)

151 μs ± 18.7 μs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [44]:
x = np.ones((2,3, 7, 5))
weights = np.array([1, 2, 3, 4, 5])
x = x * weights
x

array([[[[1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.]],

        [[1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.]],

        [[1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.]]],


       [[[1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.]],

        [[1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.],
         [1., 2., 3., 4., 5.]

In [6]:
np.linspace(-90, 90, 121)

array([-90. , -88.5, -87. , -85.5, -84. , -82.5, -81. , -79.5, -78. ,
       -76.5, -75. , -73.5, -72. , -70.5, -69. , -67.5, -66. , -64.5,
       -63. , -61.5, -60. , -58.5, -57. , -55.5, -54. , -52.5, -51. ,
       -49.5, -48. , -46.5, -45. , -43.5, -42. , -40.5, -39. , -37.5,
       -36. , -34.5, -33. , -31.5, -30. , -28.5, -27. , -25.5, -24. ,
       -22.5, -21. , -19.5, -18. , -16.5, -15. , -13.5, -12. , -10.5,
        -9. ,  -7.5,  -6. ,  -4.5,  -3. ,  -1.5,   0. ,   1.5,   3. ,
         4.5,   6. ,   7.5,   9. ,  10.5,  12. ,  13.5,  15. ,  16.5,
        18. ,  19.5,  21. ,  22.5,  24. ,  25.5,  27. ,  28.5,  30. ,
        31.5,  33. ,  34.5,  36. ,  37.5,  39. ,  40.5,  42. ,  43.5,
        45. ,  46.5,  48. ,  49.5,  51. ,  52.5,  54. ,  55.5,  57. ,
        58.5,  60. ,  61.5,  63. ,  64.5,  66. ,  67.5,  69. ,  70.5,
        72. ,  73.5,  75. ,  76.5,  78. ,  79.5,  81. ,  82.5,  84. ,
        85.5,  87. ,  88.5,  90. ])